#tomcat端口号
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8088
#datasource
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/shiro
    username : root
    password : 142857
    driverClassName : com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    database : MYSQL
# Show or not log for each sql query
    show-sql : true
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
# Naming strategy
#[org.hibernate.cfg.ImprovedNamingStrategy | org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy : org.hibernate.cfg.DefaultNamingStrategy
# stripped before adding them to the entity manager)
  properties:
    hibernate:
      dialect : org.hibernate.dialect.MySQL5Dialect